### ISSUE TITLE
gateway.istio-ingressgateway.loadBalancerIP should not be set

### ISSUE THREAD

**Issue by evanlouie** [timfpark/fabrikate-cloud-native#3]
https://github.com/timfpark/fabrikate-cloud-native/commit/599ea69aabd96b1d0f6787af70daffb11a357a60 set `gateway.istio-ingressgateway.loadBalancerIP` to `x.x.x.x`. This breaks the Ingress and will make it not be able to acquire an IP address.

@timfpark why was this set to `x.x.x.x` I don't believe it has any effect on egress traffic as the commit mentions.

**Comment by timfpark** [comment]
Removed from `fabrikate-cloud-native` and migrated to the application spec itself.
